rails-task-manager/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'task#index'
  get 'tasks/:id', to: 'task#show', as: :task
  get 'new', to: 'task#new', as: :new_task
  post 'tasks', to: 'task#create'
  get 'tasks/:id/edit', to: 'task#edit', as: :edit
  patch 'tasks/:id', to: 'task#update'
  delete 'tasks/:id', to: 'task#destroy', as: :delete
end

rails-task-manager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-task-manager/app/models/task.rb
class Task < ApplicationRecord
end

rails-task-manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-task-manager/app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

rails-task-manager/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-task-manager/app/helpers/task_helper.rb
module TaskHelper
end

rails-task-manager/app/views/task/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field  :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
  <%= link_to "Return to Tasks!", tasks_path %>
<% end %>

rails-task-manager/app/views/task/edit.html.erb
<%= render "form", task: @task %>

rails-task-manager/app/views/task/index.html.erb
<h1>All Tasks</h1>
<% @tasks.each do |task|%>
  <li>
  <%= link_to task.title, task_path(task) %>
  </li>
<% end %>
<%= link_to "add new task", new_task_path%>

rails-task-manager/app/views/task/new.html.erb
<%= render "form", task: @task %>

rails-task-manager/app/views/task/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>
<%= link_to "Return to tasks", tasks_path %>
<%= link_to "Edit this Task", edit_path(@task) %>
<%= link_to "Delete This Task", delete_path(@task), method: :delete %>