rails-simple-airbnb/config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails-simple-airbnb/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-simple-airbnb/app/models/flat.rb
class Flat < ApplicationRecord
end

rails-simple-airbnb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-simple-airbnb/app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]

  # GET /flats or /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

rails-simple-airbnb/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-simple-airbnb/app/helpers/flats_helper.rb
module FlatsHelper
end

rails-simple-airbnb/app/views/flats/_form.html.erb
<%= form_with(model: flat, local: true) do |form| %>
  <% if flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
        <% flat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price_per_night %>
    <%= form.number_field :price_per_night %>
  </div>

  <div class="field">
    <%= form.label :number_of_guests %>
    <%= form.number_field :number_of_guests %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails-simple-airbnb/app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

rails-simple-airbnb/app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All our Flats (<%= @flats.count %>)</h1>

<tbody>
  <div id = "wraper">
  <% @flats.each do |flat| %>
    <div id = 'cards'>
        <div class = "flat-card-image" style = "background-image: url('https://picsum.photos/200/300')"></div>
        <div id ='flat-name'>
          <p><%= flat.name %></p>
          <p><%= flat.address %></p>
          <p>People:<%= "#{flat.price_per_night}"%> $<%= "#{flat.number_of_guests}"%></p>
        </div>
        <div id = 'actions'>
          <%= link_to 'More Info', flat %>
          <%= link_to 'Edit', edit_flat_path(flat) %>
          <%= link_to 'Remove', flat, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
  <% end %>
  </div>
</tbody>

<br>

<%= link_to 'New Flat', new_flat_path %>

rails-simple-airbnb/app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path %>

rails-simple-airbnb/app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flat.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @flat.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flat.description %>
</p>

<p>
  <strong>Price per night:</strong>
  <%= @flat.price_per_night %>
</p>

<p>
  <strong>Number of guests:</strong>
  <%= @flat.number_of_guests %>
</p>

<%= link_to 'Edit', edit_flat_path(@flat) %> |
<%= link_to 'Back', flats_path %>

rails-simple-airbnb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>